
# Configuration for async io system
[asyncIO]
	# (Default: 2) IO worker executor parallelism
	serializerParallelism = 2
	# (Default: true) Whether to enable this feature
	enabled = true

# Configuration for threaded world generation
[threadedWorldGen]
	# (Default: false) Whether to allow feature generation (world decorations like trees, ores and etc.) run in parallel 
	# (may cause incompatibility with other mods)
	allowThreadedFeatures = false
	# (Default: 2) World generation worker executor parallelism
	parallelism = 6
	# (Default: false) Whether to allow reducing lock radius (faster but UNSAFE) (YOU HAVE BEEN WARNED) 
	# (may cause incompatibility with other mods)
	reduceLockRadius = false
	# (Default: false) (Experimental) Whether to enable global BiomeCache to accelerate worldgen 
	# This increases memory allocation 
	useGlobalBiomeCache = false
	# (Default: true) Whether to enable this feature
	enabled = true

